### ISSUE TITLE
error on missing attestation cert: get attestation cert: data object or application not found

### ISSUE THREAD

**Issue by rdslw** [FiloSottile/yubikey-agent#71] opened 2021-01-02 12:55 UTC
We're using yubikeys (4.3) which contain preloaded keys to reach specific requirement for keys which are not possible with them being generated on the yubikey itself. Hence no attestion certs on the yubikey for imported keys.

yubikey-agent errors (on key usage via ssh) with:
```
2021/01/02 11:57:33 Connecting to the YubiKey...
2021/01/02 11:59:38 agent 13: failed to prepare private key: get attestation cert: data object or application not found
```

How is it possible to work around it and use such yubikeys? (Just to be clear, they're NOT provisioned using --setup option)

**Comment by FiloSottile** [comment] 2021-07-24 15:35
Duplicate of #91

**Closed by FiloSottile** 2021-07-24 15:35 UTC
